config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # 静的ページの設定
  get "help", to: "static_pages#help"
  get "privacy", to: "static_pages#privacy"
  get "terms", to: "static_pages#terms"

  # トップページ設定
  get "/", to: "top#index", as: "top"
  get "references/networks", to: "references#networks"
  get "references/jsons", to: "references#jsons"

  # lessonsのパス設定
  get "lessons", to: "lessons#index", as: "lesson_index_path"
  resources :lessons, only: [:show]
  post "lessons/check", to: "lessons#check"

  # inquiriesのパス設定
  resources :inquiries, only: [:new, :create]

  # usersのパス設定
  get "users/:id/edit", to: "users#edit", as: :edit_user_get
  patch "users/:id", to: "users#update", as: :edit_user_patch
  put "users/:id", to: "users#update", as: :edit_user_put
  get "users/account/:id", to: "users#show", as: :show_users

  # deviseの設定
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  validates :question_id, uniqueness: { scope: :user_id }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  attachment :image

  validates :genre, { presence: true }
  validates :inquiery, { presence: true }
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_many :questions, dependent: :nullify
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :lesson
  has_many :choices, dependent: :nullify
end

app/models/user.rb
class User < ApplicationRecord
  attachment :image

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  validates :name, presence: true, length: { maximum: 20 }
  validates :agreement, acceptance: true
end

# jquery form validation

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  def new
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new(inquiry_param)
    if @inquiry.save
      flash[:notice] = "投稿が完了しました"
      redirect_to top_path, notice: "投稿が完了しました"
    else
      flash[:notice] = "投稿に失敗しました"
      render :new
    end
  end

  private

  def inquiry_param
    params.require(:inquiry).permit(:genre, :name, :email, :inquiery, :image)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
    @lesson = Lesson.all.order(id: "ASC")
    @question = Question.all
  end

  def show
    @question = Question.where(lesson_id: params[:id]).sample
    @lesson = Lesson.find_by(id: params[:id])
    @choices = @question.choices.where(lesson_id: @lesson.id).shuffle
    @answered = []
  end

  def check
    @answered = choice_params[:answered]&.permit! || []
    @answered.push({ choice_id: choice_params[:choice_id], question_id: choice_params[:question_id] })

    answered_question_ids = @answered.pluck(:question_id)
    question = Question.find(choice_params[:question_id])
    @correct_answer = question.choices.find_by(is_answer: true)
    @question = question.lesson.questions.where.not(id: answered_question_ids).sample
    @choices = @question.choices.where(lesson_id: question.lesson_id).shuffle
    choice = Choice.find(choice_params[:choice_id])
    @correctness = if choice.is_answer
                     "正解"
                   else
                     "不正解"
                   end
  end

  def references
    @lesson = Lesson.find_by(id: params[:id])
  end

  private

  def choice_params
    params.permit(:choice_id, :question_id, answered: [])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "ユーザーを更新しました"
      redirect_to :edit_user_get
    else
      flash[:notice] = "ユーザーを更新できませんでした"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/jsons_helper.rb
module JsonsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/networks_helper.rb
module NetworksHelper
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/top/index.html.erb
<section class="hero is-medium is-bold" style="background-color: #CAE5CD;">
  <div class="hero-body">
    <div class="container has-text-centered">
      <div class="is-flex-tablet justify-content-center align-items-center">
        <ul>
          <li>
            <h1 class="m-3 add-font-bold is-size-2">
              ネットワークエンジニアの<br/>ためのコアな学習サイト
            </h1>
          </li>
          <li>
            <% unless user_signed_in? %>
              <%= link_to(new_user_registration_path, class: "button is-info has-text-weight-bold w-50 is-medium mt-4 text-decoration-none") do %>
                ユーザー登録
              <% end %>
            <% end %>
          </li>
          <li>
            <a class="button is-primary w-50 text-decoration-none mt-4" id="button_lesson" href="/lessons">すぐにレッスンを受講</a>
          </li>
        </ul>
        <%= image_tag asset_path("job_programmer.jpg"), :width => '250', :height => '250' %>
      </div>
    </div>
  </div>
</section>
<section class="container">
  <div class="column is-8 is-offset-2 my-5 has-text-centered">
    <h2 class="title mb-5 add-font-regular">問題一覧</h2>
  </div>
  <div class="columns my-5">
    <div class="column is-4">
      <div class="card has-text-centered">
        <div class="card-image">
          <figure class="image is-4by3">
            <%= link_to(lesson_index_path_path(anchor: 'network')) do %>
              <%= image_tag asset_path("network.jpg") %>
            <% end %>
          </figure>
        </div>
        <div class="card-content">
          <div class="content">
            <h4 class="add-font-bold">
              <%= link_to(lesson_index_path_path(anchor: 'network'), class:"has-text-grey-darker") do %>
                ネットワーク機器に関する問題
              <% end %>
            </h4>
            <p>
              ネットワークの設計図で出てくる機器のアイコンに関する問題です(Ciscoアイコン)。設計、監視・運用業務でネットワークの設計図を見ることは多いと思われます。未経験の方には参考になると思われますので、ぜひトライしてみましょう！
            </p>
            <p>
              <%= link_to(lesson_index_path_path(anchor: 'network'), class:"button is-info w-100 mt-2 text-decoration-none") do %>
              <%# <%= link_to "ネットワーク機器に関する問題",lesson_path(1), class:"button is-info w-100 mt-2 text-decoration-none" %>
                ネットワーク機器に関する問題
              <% end %>
            </p>
          </div>
        </div>
      </div>
    </div>
    <div class="column is-4">
      <div class="card has-text-centered">
        <div class="card-image">
          <figure class="image is-4by3">
            <%= link_to(lesson_index_path_path(anchor: 'json')) do %>
              <%= image_tag asset_path("json.jpg") %>
            </a>
          </figure>
          <% end %>
        </div>
        <div class="card-content">
          <div class="content">
            <h4 class="add-font-bold">
              <%= link_to(lesson_index_path_path(anchor: 'json'), class:"has-text-grey-darker") do %>
                Zabbixで使われるJSON問題編
              <% end %>
            </h4>
            <p>
              Zabbixとは主に運用・監視業務で使われる、システムの監視を自動化するツールのこと。Zabbix API(ZabbixのWeb管理画面で行ったさまざまな操作を管理画面を使用せずに行える)によって、JSON形式でデータのやり取りができる。(恐らくネットワークエンジニアでもプログラムが書ける人しか使わないと思われる)
            </p>
            <%= link_to(lesson_index_path_path(anchor: 'json'), class:"button is-info w-100 mt-2 text-decoration-none") do %>
              問題編
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="column is-4">
      <div class="card has-text-centered">
        <div class="card-image">
          <figure class="image is-4by3">
            <%= image_tag asset_path("no_image.jpg") %>
          </figure>
        </div>
        <div class="card-content">
          <div class="content">
            <h4 class="add-font-bold has-text-grey-darker">
              募集中
            </h4>
            <p>
              現在新たな種類の問題を募集しています。問題を考えて下さった方は「お問い合わせフォーム」から投稿をお願いいたします🙇‍♀️
            </p>
            <button class="button is-info w-100 mt-2 text-decoration-none" disabled="disable">募集中
          </div>
        </div>
      </div>
    </div>
  </div>
</section>