config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # 静的ページの設定
  get "help", to: "static_pages#help"
  get "privacy", to: "static_pages#privacy"
  get "terms", to: "static_pages#terms"

  # トップページ設定
  get "/", to: "top#index", as: "top"
  get "references/networks", to: "references#networks"
  get "references/jsons", to: "references#jsons"

  # lessonsのパス設定
  get "lessons", to: "lessons#index", as: "lesson_index_path"
  resources :lessons, only: [:show]
  post "lessons/check", to: "lessons#check"

  # inquiriesのパス設定
  resources :inquiries, only: [:new, :create]

  # usersのパス設定
  get "users/:id/edit", to: "users#edit", as: :edit_user_get
  patch "users/:id", to: "users#update", as: :edit_user_patch
  put "users/:id", to: "users#update", as: :edit_user_put
  get "users/account/:id", to: "users#show", as: :show_users

  # deviseの設定
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  validates :question_id, uniqueness: { scope: :user_id }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  attachment :image

  validates :genre, { presence: true }
  validates :inquiery, { presence: true }
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_many :questions, dependent: :nullify
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :lesson
  has_many :choices, dependent: :nullify
end

app/models/user.rb
class User < ApplicationRecord
  attachment :image

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  validates :name, presence: true, length: { maximum: 20 }
  validates :agreement, acceptance: true
end

# jquery form validation

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :null_session

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:email, :encrypted_password, :name, :profile, :occupation, :position,
                                             :agreement])
  end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  def new
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.new(inquiry_param)
    if @inquiry.save
      flash[:notice] = "投稿が完了しました"
      redirect_to top_path, notice: "投稿が完了しました"
    else
      flash[:notice] = "投稿に失敗しました"
      render :new
    end
  end

  private

  def inquiry_param
    params.require(:inquiry).permit(:genre, :name, :email, :inquiery, :image)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
    @lesson = Lesson.all.order(id: "ASC")
    @question = Question.all
  end

  def show
    @question = Question.where(lesson_id: params[:id]).sample
    @lesson = Lesson.find_by(id: params[:id])
    @choices = @question.choices.where(lesson_id: @lesson.id).shuffle
    @answered = []
  end

  def check
    @answered = choice_params[:answered]&.permit! || []
    @answered.push({ choice_id: choice_params[:choice_id], question_id: choice_params[:question_id] })

    answered_question_ids = @answered.pluck(:question_id)
    question = Question.find(choice_params[:question_id])
    @correct_answer = question.choices.find_by(is_answer: true)
    @question = question.lesson.questions.where.not(id: answered_question_ids).sample
    @choices = @question.choices.where(lesson_id: question.lesson_id).shuffle
    choice = Choice.find(choice_params[:choice_id])
    @correctness = if choice.is_answer
                     "正解"
                   else
                     "不正解"
                   end
  end

  def references
    @lesson = Lesson.find_by(id: params[:id])
  end

  private

  def choice_params
    params.permit(:choice_id, :question_id, answered: [])
  end
end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController
  def networks; end

  def jsons; end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "ユーザーを更新しました"
      redirect_to :edit_user_get
    else
      flash[:notice] = "ユーザーを更新できませんでした"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/jsons_helper.rb
module JsonsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/networks_helper.rb
module NetworksHelper
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/lessons/networks/index.html.erb
<div class="container my-4">
  <h1 class="title has-text-centered is-hidden-mobile">ネットワーク機器一覧</h1>
  <h1 class="title has-text-centered is-size-4 is-hidden-tablet">ネットワーク機器一覧</h1>
  <div class="row">
    <div class="column is-6 is-offset-3">
      <table class="table is-hoverable">
        <thead>
          <tr>
            <th class="is-hidden-mobile" scope="col">参考資料</th>
            <th class="is-hidden-mobile" scope="col">説明</th>
          </tr>
        </thead>
        <tbody>
        <tr>
          <td class="has-text-weight-semibold"><%= image_tag asset_path("レイヤー画像.jpg"), :width => '300', :height => '300' %><br>(出典：http://atnetwork.info/)</td>
          <td class="has-text-weight-semibold">階層別のネットワーク機器</td>
        </tr>
        </tbody>
        <tbody>
        <tr>
          <td class="has-text-weight-semibold"><%= image_tag asset_path("マルチレイヤ.jpg"), :width => '220', :height => '220' %><%= image_tag asset_path("maltilayer.jpg"), :width => '100', :height => '100' ,class:"device_figure"%></td>
          <td class="has-text-weight-semibold">マルチレイヤー</td>
        </tr>
        </tbody>
        <tbody>
        <tr>
          <td class="has-text-weight-semibold"><%= image_tag asset_path("スイッチ.jpg"), :width => '220', :height => '220' %><%= image_tag asset_path("switch.jpg"), :width => '100', :height => '100' ,class:"device_figure"%></td>
          <td class="has-text-weight-semibold">スイッチ</td>
        </tr>
        </tbody>
        <tbody>
        <tr>
          <td class="has-text-weight-semibold"><%= image_tag asset_path("スイッチングハブ.jpg"), :width => '220', :height => '220' %><%= image_tag asset_path("hub.jpg"), :width => '100', :height => '100' ,class:"device_figure"%></td>
          <td class="has-text-weight-semibold">スイッチングハブ</td>
        </tr>
        </tbody>
        <tbody>
        <tr>
          <td class="has-text-weight-semibold"><%= image_tag asset_path("モデム.jpg"), :width => '220', :height => '220' %><%= image_tag asset_path("modem.jpg"), :width => '100', :height => '100' ,class:"device_figure"%></td>
          <td class="has-text-weight-semibold">モデム</td>
        </tr>
        </tbody>
        <tbody>
        <tr>
          <td class="has-text-weight-semibold"><%= image_tag asset_path("アクセスポイント.jpg"), :width => '220', :height => '220' %><%= image_tag asset_path("AP.jpg"), :width => '110', :height => '110' ,class:"device_figure"%></td>
          <td class="has-text-weight-semibold">アクセスポイント</td>
        </tr>
        </tbody>
        <tbody>
        <tr>
          <td class="has-text-weight-semibold"><%= image_tag asset_path("クラウド.jpg"), :width => '220', :height => '220' %><%= image_tag asset_path("cloud.jpg"), :width => '110', :height => '110' ,class:"device_figure"%></td>
          <td class="has-text-weight-semibold">クラウド</td>
        </tr>
        </tbody>
        <tbody>
        <tr>
          <td class="has-text-weight-semibold"><%= image_tag asset_path("ファイアウォール.jpg"), :width => '220', :height => '220' %><%= image_tag asset_path("firewall.jpg"), :width => '110', :height => '110' ,class:"device_figure"%></td>
          <td class="has-text-weight-semibold">ファイアウォール</td>
        </tr>
        </tbody>
        <tbody>
        <tr>
          <td class="has-text-weight-semibold"><%= image_tag asset_path("オーエヌユー.jpg"), :width => '220', :height => '220' %><%= image_tag asset_path("onu.jpg"), :width => '110', :height => '110' ,class:"device_figure"%></td>
          <td class="has-text-weight-semibold">ONU(光終端装置)</td>
        </tr>
        </tbody>
        <tbody>
        <tr>
          <td class="has-text-weight-semibold"><%= image_tag asset_path("malti-single_mode.jpg"), :width => '240', :height => '250' %></td>
          <td class="has-text-weight-semibold">シングルモード・マルチモード</td>
        </tr>
        </tbody>
        <tbody>
        <tr>
          <td class="has-text-weight-semibold"><%= image_tag asset_path("メディアコンバーター.jpg"), :width => '240', :height => '250' %></td>
          <td class="has-text-weight-semibold">メディアコンバータ</td>
        </tr>
        </tbody>
        <tbody>
        <tr>
          <td class="has-text-weight-semibold">上にカーソル移動</td>
          <td class="has-text-weight-semibold">k</td>
        </tr>
        </tbody>
        <tbody>
        <tr>
          <td class="has-text-weight-semibold">上にカーソル移動</td>
          <td class="has-text-weight-semibold">k</td>
        </tr>
        </tbody>
        <tbody>
        <tr>
          <td class="has-text-weight-semibold">上にカーソル移動</td>
          <td class="has-text-weight-semibold">k</td>
        </tr>
        </tbody>
        <tbody>
        <tr>
          <td class="has-text-weight-semibold">上にカーソル移動</td>
          <td class="has-text-weight-semibold">k</td>
        </tr>
        </tbody>
        <tbody>
        <tr>
          <td class="has-text-weight-semibold">上にカーソル移動</td>
          <td class="has-text-weight-semibold">k</td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="column is-6 is-offset-3 has-text-centered">
      <a class="button is-primary is-outlined is-rounded text-decoration-none" data-turbolinks="false" href="/lessons/network-02/exam">
        <span class="mr-1">
          <svg class="svg-inline--fa fa-caret-square-right fa-w-14" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="caret-square-right" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" data-fa-i2svg="">
            <path fill="currentColor" d="M48 32h352c26.51 0 48 21.49 48 48v352c0 26.51-21.49 48-48 48H48c-26.51 0-48-21.49-48-48V80c0-26.51 21.49-48 48-48zm140.485 355.515l123.029-123.029c4.686-4.686 4.686-12.284 0-16.971l-123.029-123.03c-7.56-7.56-20.485-2.206-20.485 8.485v246.059c0 10.691 12.926 16.045 20.485 8.486z"></path>
          </svg><!-- <i class="fas fa-caret-square-right"></i> Font Awesome fontawesome.com -->
        </span>Vim中級編はこちら
      </a>
    </div>
  </div>
</div>

app/views/lessons/networks/show.html.erb
<%# <%= render "shared/error", obj:@network %> 

<div class = "whole"> 
  <div id="container">
     <h1>Q. What is A?</h1>
     <ul>
       <li class="answer">A0</li>
       <li class="answer">A1</li>
       <li class="answer">A2</li>
       <li class="answer">A3</li>
     </ul>
     <div id="btn" class="disabled">Next Question</div>
   </div>
 </div>
 <div>
 
 <%# <%= form_with  method: :get, local: true do |f|%>
<%# <%= button_to '次の問題へ', new_lessons_path(f.id), method: :post, remote: true %>
<%# <% end %> 


<%# <% quizSet = [] %> 
<%# <%= 
  question = 'What is A?',
  answer = ['A0', 'A1', 'A2', 'A3'] 

 quizSet[] = [
  question = 'What is B?',
  answer = ['B0', 'B1', 'B2', 'B3']
] 

quizSet[] = [
  question => 'What is C?',
  answer => ['C0', 'C1', 'C2', 'C3']
]
current_num = 0 

 data = quizSet[$current_num]
shuffle(data[a])%> 

  <script>
  let questionArr = <%= @quetions %>
  let answers = []


  [[{ answer: 'this is a', correct: false }, { answer: 'this is b', correct: false } ,{ answer: 'this is c', correct: false }, { answer: 'this is a', correct: true }]] 
  function answer (choosed) {
    answers << choosed ? true : false
    // show result animation o or x by jquery
    answers.unshift()
    if (answers.length === 0) {
      // move to result
    }
  }
  </script>