config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # 静的ページの設定
  get "help", to: "static_pages#help"
  get "privacy", to: "static_pages#privacy"
  get "terms", to: "static_pages#terms"

  # トップページ設定
  get "/", to: "top#index", as: "top"
  get "references/networks", to: "references#networks"
  get "references/jsons", to: "references#jsons"

  # lessonsのパス設定
  get "lessons", to: "lessons#index", as: "lesson_index_path"
  resources :lessons, only: [:show]
  post "lessons/check", to: "lessons#check"

  # inquiriesのパス設定
  resources :inquiries, only: [:new, :create]

  # usersのパス設定
  get "users/:id/edit", to: "users#edit", as: :edit_user_get
  patch "users/:id", to: "users#update", as: :edit_user_patch
  put "users/:id", to: "users#update", as: :edit_user_put
  get "users/account/:id", to: "users#show", as: :show_users

  # deviseの設定
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
end

app/models/user.rb
class User < ApplicationRecord
  attachment :image

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  validates :name, presence: true, length: { maximum: 20 }
  validates :agreement, acceptance: true
end

# jquery form validation

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  skip_before_action :verify_authenticity_token, only: :create

  # GET /resource/sign_up
  # def new
  #   # super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "ユーザーを更新しました"
      redirect_to :edit_user_get
    else
      flash[:notice] = "ユーザーを更新できませんでした"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container-fiuld user">
  <div class="row">
    <div class="col-lg-2 user-nav user-nav-pc d-lg-block d-none">
      <ul>
        <li class="">
          <%=link_to(show_users_path(@user.id)) do %>
          <%# <%= link_to("アカウント", "/users/account/#{@user.id}") %>
          <%# <a href="/users/account/:id">アカウント</a> %>
          アカウント
          <% end %>
        </li>
        <li class="active">
          <a href="/users">プロフィール</a>
        </li>
      </ul>
    </div>
    <div class="col-lg-2 user-nav user-nav-mobile d-lg-none">
      <ul>
        <li class="">
          <%=link_to(show_users_path(@user.id)) do %>
          <%# <%= link_to("アカウント", "/users/account") %>
          アカウント
          <% end %>
        </li>
        <%# <li class=""><a href="/users/account">アカウント</a></li> %>
        <li class="active">
          <a href="/users">プロフィール</a>
        </li>
      </ul>
    </div>
    <div class="col-lg-10 user-view">
      <div class="user-view-box">
        <div class="update-content">
          <div class="row">
          </div>
        </div>
        <%= form_for @user, url: edit_user_put_path, methods: :put do |f| %>
          <div class="update-content">
            <div class="row">
              <div class="col-md-6 offset-md-3">
                <div class="icon-box">
                  <% if @user.image != nil %>
                    <%= image_tag attachment_url(@user, :image, :fill, 60, 60),class: "icon-image host-icon" %>
                  <% else %>
                    <%= image_tag "https://presite-potepancamp-rails-02.herokuapp.com/assets/default_icon-9263fc59c414b7228d256fc178dcb22183561357950a68f5ad086ba7ee054974.jpg",class: "icon-image host-icon" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.label :image , "アイコン画像" ,class:"col-md-3"%>
              <%# <label class="col-md-3 required-a" for="image">アイコン画像</label> %>
              <%= f.attachment_field :image , class:"mb-4 col-md-9",placeholder:"アイコン画像をアップロード" %>
              <%# <input class="mb-4 col-md-9" placeholder="アイコン画像をアップロード" type="file" name="user[image]" id="user_image"> %>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.label :name ,"名前" ,class:"col-md-3 required-a"%>
              <%# <label class="col-md-3 required-a" for="name">名前</label> %>
              <%= f.text_field :name ,class:"col-md-3 required-a name-adjust", placeholder:"名前を入力", id:"user_name"%>
              <%# <input class="form-control mb-4 col-md-9" placeholder="名前を入力" type="text" value="aaaaa" name="user[name]" id="user_name"> %>
              <%# <%= render "shared/error", obj: @user %> 
              <div class="name-error">
                <%= render "shared/error", obj: @user %>
              </div>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.label :introduction ,"自己紹介" ,class:"col-md-3 "%>
              <%# <label class="col-md-3 required-a" for="introduction">自己紹介</label> %>
              <%= f.text_area :introduction ,class:"form-control mb-4 col-md-9" ,placeholder:"自己紹介を入力" %>
              <%# <textarea rows="5" class="form-control mb-4 col-md-9" placeholder="自己紹介を入力" name="user[introduction]" id="user_introduction"></textarea> %>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.submit "更新" ,class:"col-md-2 btn btn-primary mx-3"%>
              <%# <input type="submit" name="commit" value="更新" class="col-md-2 btn btn-primary mx-3" data-disable-with="更新"> %>
            </div>
          </div>          
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container-fiuld user">
  <div class="row">
    <div class="col-lg-2 user-nav user-nav-pc d-lg-block d-none">
      <ul>
        <li class="">
          <%=link_to(show_users_path(@user.id)) do %>
          <%# <%= link_to("アカウント", "/users/account/#{@user.id}") %>
          <%# <a href="/users/account/:id">アカウント</a> %>
          アカウント
          <% end %>
        </li>
        <li class="active">
          <a href="/users">プロフィール</a>
        </li>
      </ul>
    </div>
    <div class="col-lg-2 user-nav user-nav-mobile d-lg-none">
      <ul>
        <li class="">
          <%=link_to(show_users_path(@user.id)) do %>
          <%# <%= link_to("アカウント", "/users/account") %>
          アカウント
          <% end %>
        </li>
        <%# <li class=""><a href="/users/account">アカウント</a></li> %>
        <li class="active">
          <a href="/users">プロフィール</a>
        </li>
      </ul>
    </div>
    <div class="col-lg-10 user-view">
      <div class="user-view-box">
        <div class="update-content">
          <div class="row">
          </div>
        </div>
        <%= form_for @user, url: users_index_path(current_user.id), methods: :patch do |f| %>
        <%# <form class="edit_user" id="edit_user_744" enctype="multipart/form-data" action="/users/profile" accept-charset="UTF-8" method="post"> %>
          <input type="hidden" name="_method" value="patch">
          <input type="hidden" name="authenticity_token" value="8iI4iI6VCVKGx0/eBrB6Xq5n5wDh2Xlly7YQE4zzdBLYcp3icK49pZ9YiZlvSbeUBiXFukAuLwcaGwp/vQNZkw==">
          <div class="update-content">
            <div class="row">
              <div class="col-md-6 offset-md-3">
                <div class="icon-box">
                  <% if @user.image != nil %>
                    <%= image_tag attachment_url(@user, :image, :fill, 60, 60),class: "icon-image host-icon" %>
                  <% else %>
                    <%= image_tag "https://presite-potepancamp-rails-02.herokuapp.com/assets/default_icon-9263fc59c414b7228d256fc178dcb22183561357950a68f5ad086ba7ee054974.jpg",class: "icon-image host-icon" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.label :image , "アイコン画像" ,class:"col-md-3 required-a"%>
              <%# <label class="col-md-3 required-a" for="image">アイコン画像</label> %>
              <%= f.attachment_field :image , class:"mb-4 col-md-9",placeholder:"アイコン画像をアップロード" %>
              <%# <input class="mb-4 col-md-9" placeholder="アイコン画像をアップロード" type="file" name="user[image]" id="user_image"> %>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.label :name ,"名前" ,class:"col-md-3 required-a"%>
              <%# <label class="col-md-3 required-a" for="name">名前</label> %>
              <%= f.text_field :name ,class:"col-md-3 required-a", placeholder:"名前を入力"%>
              <%# <input class="form-control mb-4 col-md-9" placeholder="名前を入力" type="text" value="aaaaa" name="user[name]" id="user_name"> %>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.label :introduction ,"自己紹介" ,class:"col-md-3 required-a"%>
              <%# <label class="col-md-3 required-a" for="introduction">自己紹介</label> %>
              <%= f.text_area :introduction ,class:"form-control mb-4 col-md-9" ,placeholder:"自己紹介を入力" %>
              <%# <textarea rows="5" class="form-control mb-4 col-md-9" placeholder="自己紹介を入力" name="user[introduction]" id="user_introduction"></textarea> %>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.submit "更新" ,class:"col-md-2 btn btn-primary mx-3"%>
              <%# <input type="submit" name="commit" value="更新" class="col-md-2 btn btn-primary mx-3" data-disable-with="更新"> %>
            </div>
          </div>          
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container-fiuld user">
  <div class="row">
    <div class="col-lg-2 user-nav user-nav-pc d-lg-block d-none">
      <ul>
        <li class="">
          <%=link_to(show_users_path(@user.id)) do %>
          <%# <%= link_to("アカウント", "/users/account/#{@user.id}") %>
          <%# <a href="/users/account/:id">アカウント</a> %>
          アカウント
          <% end %>
        </li>
        <li class="active">
          <a href="/users">プロフィール</a>
        </li>
      </ul>
    </div>
    <div class="col-lg-2 user-nav user-nav-mobile d-lg-none">
      <ul>
        <li class="">
          <%=link_to(show_users_path(@user.id)) do %>
          <%# <%= link_to("アカウント", "/users/account") %>
          アカウント
          <% end %>
        </li>
        <%# <li class=""><a href="/users/account">アカウント</a></li> %>
        <li class="active">
          <a href="/users">プロフィール</a>
        </li>
      </ul>
    </div>
    <div class="col-lg-10 user-view">
      <div class="user-view-box">
        <div class="update-content">
          <div class="row">
          </div>
        </div>
        <%= form_for @user, url: users_index_path, methods: :patch do |f| %>
        <form class="edit_user" id="edit_user_744" enctype="multipart/form-data" action="/users/profile" accept-charset="UTF-8" method="post">
          <input type="hidden" name="_method" value="patch">
          <input type="hidden" name="authenticity_token" value="8iI4iI6VCVKGx0/eBrB6Xq5n5wDh2Xlly7YQE4zzdBLYcp3icK49pZ9YiZlvSbeUBiXFukAuLwcaGwp/vQNZkw==">
          <div class="update-content">
            <div class="row">
              <div class="col-md-6 offset-md-3">
                <div class="icon-box">
                  <% if @user.image != nil %>
                    <%= image_tag attachment_url(@user, :image, :fill, 60, 60),class: "icon-image host-icon" %>
                  <% else %>
                    <%= image_tag "https://presite-potepancamp-rails-02.herokuapp.com/assets/default_icon-9263fc59c414b7228d256fc178dcb22183561357950a68f5ad086ba7ee054974.jpg",class: "icon-image host-icon" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.label :image , "アイコン画像" ,class:"col-md-3 required-a"%>
              <%# <label class="col-md-3 required-a" for="image">アイコン画像</label> %>
              <%= f.attachment_field :image , class:"mb-4 col-md-9",placeholder:"アイコン画像をアップロード" %>
              <%# <input class="mb-4 col-md-9" placeholder="アイコン画像をアップロード" type="file" name="user[image]" id="user_image"> %>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.label :name ,"名前" ,class:"col-md-3 required-a"%>
              <%# <label class="col-md-3 required-a" for="name">名前</label> %>
              <%= f.text_field :name ,class:"col-md-3 required-a", placeholder:"名前を入力"%>
              <%# <input class="form-control mb-4 col-md-9" placeholder="名前を入力" type="text" value="aaaaa" name="user[name]" id="user_name"> %>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.label :introduction ,"自己紹介" ,class:"col-md-3 required-a"%>
              <%# <label class="col-md-3 required-a" for="introduction">自己紹介</label> %>
              <%= f.text_area :introduction ,class:"form-control mb-4 col-md-9" ,placeholder:"自己紹介を入力" %>
              <%# <textarea rows="5" class="form-control mb-4 col-md-9" placeholder="自己紹介を入力" name="user[introduction]" id="user_introduction"></textarea> %>
            </div>
          </div>
          <div class="update-content">
            <div class="row">
              <%= f.submit "更新" ,class:"col-md-2 btn btn-primary mx-3"%>
              <%# <input type="submit" name="commit" value="更新" class="col-md-2 btn btn-primary mx-3" data-disable-with="更新"> %>
            </div>
          </div>          
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fiuld user"> 
  <div class="row">
    <div class="col-lg-2 user-nav user-nav-pc d-lg-block d-none">
      <ul>
        <li class="active">
          <%= link_to("アカウント", show_users_path) %>
          <%# <a href="/users/account/">アカウント</a> %>
        </li>
        <li class="">
          <%= link_to("プロフィール", show_users_path) %>
        </li>
      </ul>
    </div>
    <div class="col-lg-2 user-nav user-nav-mobile d-lg-none">
      <ul>
        <li class="active">
          <%= link_to("アカウント", show_users_path) %>
          <%# <a href="/users/account">アカウント</a> %>
        </li>
        <li class="">
          <%= link_to("プロフィール", show_users_path) %>
        </li>
      </ul>
    </div>
    <div class="col-md-10 user-view">
      <div class="user-view-box">
        <div class="update-content">
          <div class="row">
            <h5>アカウント</h5>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <label class="col-md-3" for="email">メールアドレス</label>
            <div class="col-md-9"><%= @user.email%>
            </div>
          </div>
        </div>
        <div class="update-content">
          <div class="row">
            <a class="col-md-2 btn btn-primary mx-3" href="/users/edit">アカウント編集</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>