config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # 静的ページの設定
  get "help", to: "static_pages#help"
  get "privacy", to: "static_pages#privacy"
  get "terms", to: "static_pages#terms"

  # トップページ設定
  get "/", to: "top#index", as: "top"
  get "references/networks", to: "references#networks"
  get "references/jsons", to: "references#jsons"

  # lessonsのパス設定
  get "lessons", to: "lessons#index", as: "lesson_index_path"
  resources :lessons, only: [:show]
  post "lessons/check", to: "lessons#check"

  # inquiriesのパス設定
  resources :inquiries, only: [:new, :create]

  # usersのパス設定
  get "users/:id/edit", to: "users#edit", as: :edit_user_get
  patch "users/:id", to: "users#update", as: :edit_user_patch
  put "users/:id", to: "users#update", as: :edit_user_put
  get "users/account/:id", to: "users#show", as: :show_users

  # deviseの設定
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  validates :question_id, uniqueness: { scope: :user_id }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
  attachment :image

  validates :genre, { presence: true }
  validates :inquiery, { presence: true }
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_many :questions, dependent: :nullify
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :lesson
  has_many :choices, dependent: :nullify
end

app/models/user.rb
class User < ApplicationRecord
  attachment :image

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  validates :name, presence: true, length: { maximum: 20 }
  validates :agreement, acceptance: true
end

# jquery form validation

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "ユーザーを更新しました"
      redirect_to :edit_user_get
    else
      flash[:notice] = "ユーザーを更新できませんでした"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/jsons_helper.rb
module JsonsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/networks_helper.rb
module NetworksHelper
end

app/helpers/references_helper.rb
module ReferencesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_alert.html.erb
<% if flash[:notice] %>
　<div class="alert alert-info"><%= flash[:notice] %></div>
<% elsif flash[:alert] %>
  <div class="alert alert-danger"><%= flash[:alert] %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ネットワーク学習サイト</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-light" style="background-color: #fff;">
        <%=link_to(top_path, class: "navbar-brand mt-2") do %>
          <%= image_tag asset_path("modem rooter.jpg"), :width => '40', :height => '23' %>
          <%= image_tag asset_path("rogo_title.jpg"), :width => '200'%>
        <% end %>
        </a>
        <div class="collapse navbar-collapse collapse show" id="navbarSupportedContent" style>
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="button is-text has-text-weight-semibold" href="/lessons">レッスン一覧</a>
            </li>
            <li class="nav-item">
              <a class="button is-text has-text-weight-semibold" href="/help">ヘルプ</a>
            </li>
          </ul>
          <% if user_signed_in? %>
            <a aria-expanded="false" aria-haspopup="true" class="nav-link dropdown-toggle" data-toggle="dropdown">
              <% if current_user.image != nil %>
                <%= image_tag attachment_url(current_user, :image, :fill, 35, 35),class: "rounded-circle mr15" %>
              <% else %>
                <%= image_tag "https://presite-potepancamp-rails-02.herokuapp.com/assets/default_icon-9263fc59c414b7228d256fc178dcb22183561357950a68f5ad086ba7ee054974.jpg",class: "rounded-circle mr15" %>
              <% end %>
              <span class = "has-text-weight-normal has-text-grey-dark mx-2"><%= current_user.name %></span>
            </a>
            <div class="dropdown-menu dropdown-menu-right show">
              <%=link_to(edit_user_get_path(current_user), class: "dropdown-item") do %>
                <svg class="svg-inline--fa fa-user-circle fa-w-16 mr-2" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="user-circle" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512" data-fa-i2svg="">
                  <path fill="currentColor" d="M248 8C111 8 0 119 0 256s111 248 248 248 248-111 248-248S385 8 248 8zm0 96c48.6 0 88 39.4 88 88s-39.4 88-88 88-88-39.4-88-88 39.4-88 88-88zm0 344c-58.7 0-111.3-26.6-146.5-68.2 18.8-35.4 55.6-59.8 98.5-59.8 2.4 0 4.8.4 7.1 1.1 13 4.2 26.6 6.9 40.9 6.9 14.3 0 28-2.7 40.9-6.9 2.3-.7 4.7-1.1 7.1-1.1 42.9 0 79.7 24.4 98.5 59.8C359.3 421.4 306.7 448 248 448z"></path>
                </svg><!-- <i class="fas fa-user-circle mr-2"></i> Font Awesome fontawesome.com -->
                <span class="has-text-weight-medium">設定</span>
              <% end %>
              <%=link_to(destroy_user_session_path, class:"dropdown-item", rel:"nofollow", method: :delete) do %>
                <svg class="svg-inline--fa fa-sign-out-alt fa-w-16 mr-2" style="color: gray;" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="sign-out-alt" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" data-fa-i2svg="">
                  <path fill="currentColor" d="M497 273L329 441c-15 15-41 4.5-41-17v-96H152c-13.3 0-24-10.7-24-24v-96c0-13.3 10.7-24 24-24h136V88c0-21.4 25.9-32 41-17l168 168c9.3 9.4 9.3 24.6 0 34zM192 436v-40c0-6.6-5.4-12-12-12H96c-17.7 0-32-14.3-32-32V160c0-17.7 14.3-32 32-32h84c6.6 0 12-5.4 12-12V76c0-6.6-5.4-12-12-12H96c-53 0-96 43-96 96v192c0 53 43 96 96 96h84c6.6 0 12-5.4 12-12z"></path>
                </svg><!-- <i class="fas fa-sign-out-alt mr-2" style="color: gray;"></i> Font Awesome fontawesome.com -->
                <span class="has-text-weight-medium">ログアウト</span>
              <% end %>
            </div>
          <% else %>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to "ユーザ登録", new_user_registration_path, class: 'button is-info has-text-weight-bold mr-3 text-decoration-none is-hidden-mobile' %>
              <%= link_to "ユーザ登録", new_user_registration_path, class: 'button is-info is-small has-text-weight-bold my-2 ml-2 text-decoration-none is-hidden-tablet' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'button is-light text-decoration-none is-hidden-mobile' %>
              <%= link_to "ログイン", new_user_session_path, class: 'button is-light is-small ml-2 my-2 text-decoration-none is-hidden-tablet' %>
            </li>
          </ul>
          <% end %>
        </div>
      </nav>
    </header>
    <script>
      $(function() {
        $('.dropdown-toggle').click(function() {
        $('.dropdown-menu-right').toggle(1);
        })
      });
    </script>
    
    <%= render 'layouts/alert' %>
    <%= yield %>

    <section class="container is-fluid bg-light" id="footer">
      <div class="column is-6 is-offset-3">
        <p class="has-text-weight-medium has-text-centered">Copyright © Network Study</p>
        <div class="has-text-centered is-flex-tablet justify-content-center ml-4">
        <%= link_to "利用規約" , terms_path, class:"dropdown-item" %>
        <%= link_to "プライバシーポリシー" , privacy_path, class:"dropdown-item"%>
        <%= link_to "お問い合わせ" , new_inquiry_path, class:"dropdown-item" %> 
        </a>
        </div>
      </div>
    </section>
  </body>
</html>

app/views/shared/_error.html.erb
   <% if obj.errors.any? %>
      <% obj.errors.full_messages.each do |message| %>
        <ul>
          <li class="devise-error-messages">※<%= message %></li>
        </ul>
      <% end %>
   <% end %>